name: image_processing_exercises
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - black
  - ipython
  - jupyter
  - numpy
  - pandas
  - pip
  - pre-commit
  - pytest
  - pathlib
  - pillow
  - opencv
